const divisions = {
  automation: {
    name: 'Gabvox Automate',
    shortName: 'Automate',
    eyebrow: 'AUTOMATION SYSTEMS',
    title: 'Turn repetitive work into a better-run business.',
    cardSummary: 'Automate follow-up and repetitive work.',
    description:
      'Respond to leads sooner, keep follow-up moving, and give your team back time with business automation built around the way you work.',
    outcome: 'Fewer dropped leads. Less busywork. A clearer next step.',
    outcomes: [
      'Faster lead response',
      'Fewer manual tasks',
      'Better follow-up',
      'More booked appointments',
    ],
    services: [
      'Lead Automation',
      'CRM Automation',
      'Appointment Automation',
      'AI Voice Receptionists',
      'Customer Support Automation',
      'Business Process Automation',
      'Lead Qualification',
      'Lead Enrichment',
      'Data Synchronization',
      'Reporting Automation',
    ],
    steps: [
      ['Map the work', 'Find the handoffs, repeat tasks, and slow responses that are costing your team time.'],
      ['Design the workflow', 'Set clear triggers, ownership, and exception handling before automating a process.'],
      ['Build and improve', 'Put the system in place, test real scenarios, and make its operation understandable to your team.'],
    ],
    faqs: [
      ['What can be automated?', 'A good starting point is repetitive work with clear rules: lead routing, reminders, data updates, or appointment requests. The right scope depends on your process and existing systems.'],
      ['Will automation replace our CRM?', 'Not necessarily. The goal is to make the tools you already use work together where practical, or to recommend a simpler setup when they cannot.'],
    ],
  },
  web: {
    name: 'Gabvox Web Dev',
    shortName: 'Web Dev',
    eyebrow: 'WEBSITES & WEB APPS',
    title: 'Make your website a clearer path to a customer.',
    cardSummary: 'Build a clear, search-ready website.',
    description:
      'Build a credible, quick-loading online presence that explains what you do, helps the right people find you, and makes the next step easy.',
    outcome: 'A stronger first impression. A simpler route from visit to enquiry.',
    outcomes: [
      'Professional online presence',
      'Better SEO visibility',
      'Faster websites',
      'Higher conversion rates',
    ],
    services: [
      'Business Websites',
      'SEO Websites',
      'Landing Pages',
      'Portfolio Websites',
      'Booking Websites',
      'Agency Websites',
      'Real Estate Websites',
      'Custom Web Applications',
    ],
    steps: [
      ['Clarify the customer journey', 'Understand what visitors need to know and what action the site should make easy.'],
      ['Structure and design', 'Create a focused page hierarchy and responsive interface around your services and audience.'],
      ['Build and refine', 'Deliver accessible pages with performance and search fundamentals in place.'],
    ],
    faqs: [
      ['Will my website be search-engine friendly?', 'The site structure, page titles, descriptions, semantic markup, and performance fundamentals can be built with organic search in mind. Search placement itself cannot be guaranteed.'],
      ['Can you build booking or enquiry pages?', 'Yes. The right approach depends on the booking platform or form service you use; external integrations are confirmed before they are represented as connected.'],
    ],
  },
  combined: {
    name: 'Automate Dev',
    shortName: 'Automate Dev',
    eyebrow: 'CONNECTED BUSINESS SYSTEMS',
    title: 'Connect the website to what happens next.',
    cardSummary: 'Connect your website, CRM, and workflows.',
    description:
      'Bring your website, enquiry journey, and business workflows together so a new lead can move toward a useful human follow-up or booking.',
    outcome: 'One connected journey from first visit to the next conversation.',
    outcomes: [
      'Complete business systems',
      'Website, CRM, and automation',
      'Lead capture to booking workflows',
    ],
    services: [
      'Website and lead capture planning',
      'CRM-connected enquiry workflows',
      'Lead routing and timely follow-up',
      'Website-to-booking journeys',
      'Real estate digital systems',
      'Clinic enquiry systems',
      'Recruitment workflow systems',
      'Agency lead-to-project workflows',
    ],
    steps: [
      ['Trace the whole journey', 'Map what a customer sees online and what your team needs to do behind the scenes.'],
      ['Connect the right pieces', 'Plan the website, handoffs, and workflows as one system, with clear limits around third-party tools.'],
      ['Test the handoffs', 'Check what happens from enquiry through follow-up, including incomplete information and exceptions.'],
    ],
    faqs: [
      ['Do you build websites and automation together?', 'That is the focus of Automate Dev: plan the website and the follow-up process as one business journey.'],
      ['Can you connect any CRM or booking tool?', 'Integration depends on the platform, account access, and supported interfaces. We establish feasibility and scope before promising a connection.'],
    ],
  },
};

const industries = [
  {
    slug: 'real-estate',
    name: 'Real estate',
    selectorName: 'Real Estate',
    tier: 1,
    problem: 'Property enquiries can arrive at any hour, while agents are out showing homes or already speaking with clients.',
    opportunity: 'Capture the right details, route enquiries clearly, and help agents follow up without losing the personal conversation.',
    recommendations: {
      automation: 'Property enquiry routing and timely lead follow-up',
      web: 'A property website that makes listings and viewing enquiries easy to navigate',
      combined: 'A property enquiry journey from listing page to agent follow-up',
    },
    featured: true,
  },
  {
    slug: 'medical-clinics',
    name: 'Medical clinics',
    selectorName: 'Clinic',
    tier: 1,
    problem: 'Reception teams balance calls, appointment requests, reminders, and patient questions throughout a busy day.',
    opportunity: 'Make the enquiry and appointment journey easier to manage while keeping people in control of clinical decisions.',
    recommendations: {
      automation: 'Clinic enquiry and appointment-request workflows',
      web: 'A clear clinic website that helps visitors find services and contact options',
      combined: 'A clinic website connected to a well-defined enquiry handoff',
    },
    featured: true,
  },
  {
    slug: 'recruitment-agencies',
    name: 'Recruitment agencies',
    selectorName: 'Recruitment',
    tier: 1,
    problem: 'Candidate and employer conversations create frequent follow-ups, status changes, and handoffs between recruiters.',
    opportunity: 'Give candidates and employers a clearer first step, then help recruiters keep routine coordination moving.',
    recommendations: {
      automation: 'Candidate screening, status updates, and recruiter follow-up workflows',
      web: 'A recruitment website with distinct journeys for candidates and employers',
      combined: 'A recruitment site connected to organised candidate and employer enquiry flows',
    },
    featured: true,
  },
  {
    slug: 'insurance-agencies',
    name: 'Insurance agencies',
    selectorName: 'Insurance',
    tier: 2,
    problem: 'New quote enquiries need the right context before a team member can route them or continue the conversation.',
    opportunity: 'Ask for useful details up front and make the next human follow-up more organised.',
    recommendations: {
      automation: 'Quote enquiry qualification and follow-up workflows',
      web: 'A service-led insurance website with a focused quote enquiry path',
      combined: 'A quote journey connecting website enquiries with agency follow-up',
    },
  },
  {
    slug: 'law-firms',
    name: 'Law firms',
    tier: 2,
    problem: 'Potential clients need to understand whether a firm handles their matter and how to take a first step.',
    opportunity: 'Set clear service expectations, collect an initial enquiry, and route it for appropriate review.',
    recommendations: {
      automation: 'New enquiry routing and administrative follow-up workflows',
      web: 'A professional, accessible website organised around practice areas',
      combined: 'A practice-area enquiry journey with clear human review and follow-up',
    },
  },
  {
    slug: 'home-services',
    name: 'Home service businesses',
    tier: 2,
    problem: 'Teams on the road may not be able to respond quickly when a customer asks for a quote or a service visit.',
    opportunity: 'Collect job details consistently, route requests, and make it easier to follow up between appointments.',
    recommendations: {
      automation: 'Service request intake, job routing, and follow-up workflows',
      web: 'A service-area website that makes requesting an estimate straightforward',
      combined: 'A service website connected to an organised job-request workflow',
    },
  },
  {
    slug: 'hotels',
    name: 'Hotels',
    tier: 3,
    problem: 'Guests look for timely answers, clear room information, and a straightforward way to ask about a stay.',
    opportunity: 'Present the right information clearly and organise the enquiries that still need a personal response.',
    recommendations: {
      automation: 'Guest enquiry triage and pre-arrival communication workflows',
      web: 'A hospitality website with an easy-to-follow stay enquiry journey',
      combined: 'A guest website and enquiry handoff designed as one experience',
    },
  },
  {
    slug: 'schools-training',
    name: 'Schools & training centers',
    tier: 3,
    problem: 'Prospective learners and families need course or program information, dates, and a clear route to ask questions.',
    opportunity: 'Make program information easier to find and route admissions or enrolment enquiries to the right team.',
    recommendations: {
      automation: 'Admissions enquiry routing and prospective-student follow-up',
      web: 'A program-led website with clear course and enrolment information',
      combined: 'A program website connected to a structured admissions enquiry process',
    },
  },
  {
    slug: 'agencies',
    name: 'Agencies',
    selectorName: 'Agency',
    tier: 3,
    problem: 'A growing pipeline of prospects and active projects can create repetitive lead qualification and coordination work.',
    opportunity: 'Communicate your offer clearly and give new enquiries a consistent route into your sales process.',
    recommendations: {
      automation: 'Lead qualification, pipeline updates, and project handoff workflows',
      web: 'A focused agency website that shows the offer and encourages a relevant enquiry',
      combined: 'An agency website connected to lead qualification and project handoffs',
    },
  },
  {
    slug: 'ecommerce',
    name: 'E-commerce businesses',
    tier: 3,
    problem: 'Customer questions, order updates, and product discovery can compete with the work of running a store.',
    opportunity: 'Make product information easier to navigate and organise repeatable customer-service handoffs.',
    recommendations: {
      automation: 'Customer support triage and order communication workflows',
      web: 'A product-focused store or web experience designed around customer journeys',
      combined: 'A product website connected to a considered customer support workflow',
    },
  },
  {
    slug: 'construction',
    name: 'Construction businesses',
    selectorName: 'Construction',
    tier: 4,
    selectorOnly: true,
    problem: 'Site visits, estimate requests, and customer updates compete with time spent coordinating teams and active jobs.',
    opportunity: 'Collect project details clearly, route requests, and make follow-up easier to manage between site work.',
    recommendations: {
      automation: 'Construction estimate enquiries and job follow-up workflows',
      web: 'A construction website that explains services and makes project enquiries straightforward',
      combined: 'A construction website connected to organised estimate requests and customer follow-up',
    },
  },
];

const solutionPages = [
  {
    slug: 'real-estate-lead-response',
    path: '/automation/real-estate/',
    division: 'automation',
    industry: 'real-estate',
    title: 'Real estate lead response automation',
    seoTitle: 'Real Estate Lead Response Automation for Agents | Gabvox',
    summary: 'Explore a real estate lead response automation concept for capturing property enquiries, routing leads to agents, and organising viewing follow-up.',
    visual: {
      src: '/assets/solutions/real-estate-lead-response.webp',
      alt: 'Concept illustration comparing manual real estate lead handling with an automated enquiry, follow-up, and appointment dashboard.',
      title: 'A clearer path from property enquiry to agent follow-up',
      caption: 'This conceptual illustration shows how an enquiry might move from capture to agent follow-up and viewing coordination. The dashboard and figures are illustrative, not verified results; third-party logos in the supplied artwork do not indicate active integrations.',
    },
    sections: [
      ['The business challenge', 'Property enquiries can arrive while agents are away from their desks. If details are scattered across inboxes, timely follow-up becomes harder.'],
      ['A solution concept', 'Capture the enquiry context, route it to the right agent, and make a next-step reminder visible to the team. Any connection to listing, CRM, or messaging platforms depends on technical feasibility and agreed scope.'],
      ['A sensible first step', 'Map the enquiry sources, assignment rules, response expectations, and situations that need a person to step in.'],
    ],
  },
  {
    slug: 'clinic-appointment-workflows',
    path: '/automation/clinics/',
    division: 'automation',
    industry: 'medical-clinics',
    title: 'Clinic appointment enquiry workflows',
    summary: 'An administrative enquiry concept to help a clinic organise appointment requests and reception follow-up.',
    sections: [
      ['The business challenge', 'Reception teams handle appointment requests alongside calls and day-to-day patient support.'],
      ['A solution concept', 'Organise non-clinical appointment requests, route them to the appropriate team, and make outstanding follow-up easier to see. Clinical triage and medical advice stay with qualified people.'],
      ['A sensible first step', 'Document current channels, booking rules, privacy needs, and the exact point where staff must take over.'],
    ],
  },
  {
    slug: 'clinic-ai-receptionist',
    path: '/automation/clinics/ai-receptionist/',
    division: 'automation',
    industry: 'medical-clinics',
    title: 'AI receptionist concept for clinics',
    summary: 'A clinic reception concept for organising routine calls and appointment requests while keeping clinical decisions with qualified staff.',
    sections: [
      ['The business challenge', 'Reception teams answer routine questions while managing appointments and supporting patients who need a person.'],
      ['A solution concept', 'Define which approved administrative questions an AI receptionist may handle, how it can collect a callback request, and exactly when to transfer or direct a caller to staff. It should not diagnose, triage symptoms, or make clinical decisions.'],
      ['A sensible first step', 'Review call patterns, approved answers, privacy requirements, escalation procedures, and the clinic’s existing phone and booking systems before choosing an implementation.'],
    ],
  },
  {
    slug: 'clinic-websites',
    path: '/web-development/clinics/',
    division: 'web',
    industry: 'medical-clinics',
    title: 'Clinic websites that make the next step clear',
    summary: 'A clinic website concept that helps visitors understand services, find practical information, and contact the right team.',
    sections: [
      ['The business challenge', 'Visitors may need clear information about services, opening hours, location, and how to request an appointment.'],
      ['A solution concept', 'Organise clinic information around patient questions, make contact routes easy to find, and present an accessible mobile-first experience. Avoid promising diagnosis or treatment outcomes.'],
      ['A sensible first step', 'Gather approved service information, accessibility needs, appointment instructions, and the clinic’s preferred contact or booking process.'],
    ],
  },
  {
    slug: 'recruitment-lead-workflows',
    path: '/automation/recruitment/',
    division: 'automation',
    industry: 'recruitment-agencies',
    title: 'Recruitment workflow automation',
    summary: 'A workflow concept to help recruitment teams organise candidate and employer enquiries, status changes, and routine follow-up.',
    sections: [
      ['The business challenge', 'Candidates and employers move through different stages, creating repeated updates and handoffs between recruiters.'],
      ['A solution concept', 'Map distinct candidate and employer paths, identify routine reminders and status updates, and keep recruiter review at important decision points. Connections to an ATS or CRM depend on feasibility and agreed scope.'],
      ['A sensible first step', 'Document current recruitment stages, ownership, candidate communications, privacy requirements, and the situations that must remain a human decision.'],
    ],
  },
  {
    slug: 'real-estate-websites',
    path: '/web-development/real-estate/',
    division: 'web',
    industry: 'real-estate',
    title: 'Real estate websites built around enquiries',
    summary: 'A property website concept that helps visitors explore a firm’s offer and make a useful enquiry.',
    sections: [
      ['The business challenge', 'A property website needs to communicate local expertise and make it easy to take the next step.'],
      ['A solution concept', 'Structure the site around the properties and services a business actually offers, with clear enquiry routes and a mobile-first experience. Listing feeds or valuation tools are scoped only after their provider and integration are confirmed.'],
      ['A sensible first step', 'Review the audience, listing process, existing brand assets, and any tools the website must connect to.'],
    ],
  },
  {
    slug: 'recruitment-digital-systems',
    path: '/automate-dev/recruitment/',
    division: 'combined',
    industry: 'recruitment-agencies',
    title: 'Recruitment website and workflow systems',
    summary: 'A joined-up concept for candidate and employer enquiries, recruiter handoffs, and clear online journeys.',
    sections: [
      ['The business challenge', 'Recruiters manage different audiences and frequent follow-ups. A disconnected website and internal workflow can make handoffs harder.'],
      ['A solution concept', 'Plan distinct candidate and employer journeys, then map how their enquiries move into recruiter review and follow-up. ATS or CRM connections are subject to feasibility and scope.'],
      ['A sensible first step', 'Map current candidate and employer stages, the tools in use, and which handoffs would benefit most from clarity.'],
    ],
  },
];

const resources = [
  {
    slug: 'map-your-lead-response',
    title: 'How to map a lead response process before automating it',
    description: 'A practical starting point for finding slow handoffs and deciding what a lead workflow should do.',
    sections: [
      ['Start with the real journey', 'List every way an enquiry arrives, who sees it first, and what the customer expects next. Include missed calls, after-hours messages, and enquiries with missing details.'],
      ['Make ownership explicit', 'A workflow needs clear routing rules and a person responsible for exceptions. Write down who owns each enquiry before choosing tools.'],
      ['Define a useful response', 'Decide what information is needed, what the first acknowledgement should say, and when a human needs to take over. Do not automate promises your team cannot keep.'],
      ['Test before expanding', 'Start with one enquiry source and realistic cases. Check misrouted requests, incomplete information, and the process for pausing or correcting an automation.'],
    ],
  },
  {
    slug: 'business-website-conversion-basics',
    title: 'A useful checklist for a business website that converts',
    description: 'The essential questions to answer before asking a visitor to take the next step.',
    sections: [
      ['Say who you help', 'Make the audience and service clear near the start of the page. Use plain language customers recognise instead of a list of technologies.'],
      ['Show the next step', 'Choose one primary action that makes sense for the service, such as requesting an estimate or asking about availability. Explain what happens after it.'],
      ['Make key information easy to find', 'Prioritise services, service area, contact options, and answers to common questions. A visitor should not need to guess whether the business is relevant.'],
      ['Check the mobile experience', 'Test text size, navigation, load time, and form usability on a small screen. Keep forms limited to details that are genuinely useful.'],
    ],
  },
  {
    slug: 'website-and-automation-together',
    title: 'When a website and business automation belong together',
    description: 'A guide to deciding whether a disconnected enquiry handoff is part of your website problem.',
    sections: [
      ['Look beyond the form', 'Trace what happens after somebody submits an enquiry: where it goes, who sees it, how it is assigned, and how follow-up is recorded.'],
      ['Spot the handoff gap', 'If staff repeatedly copy information between tools or requests disappear between an inbox and a team, the service journey may need both a clearer website and a better internal workflow.'],
      ['Confirm integration constraints', 'List the current platforms, available access, and approved data flows. A connection should be confirmed against the actual tools before it is promised.'],
      ['Keep a human in the loop', 'Set expectations for review and make it possible to handle unusual or sensitive enquiries outside the automated path.'],
    ],
  },
];

module.exports = { divisions, industries, solutionPages, resources };
